# Cart
CART_PAGE=//a[contains(text(),'Cart')]
CART_FOOTER=#footer
SUBSCRIPTION_LABEL=//h2[contains(text(),'Subscription')]
INPUT_SUBSCRIBE_EMAIL=//input[@id='susbscribe_email']
SUBSCRIBE_BUTTON=//button[@id='subscribe']
SUCCESS_ALERT_MESSAGE=//div[@class='alert-success alert']
CART_TABLE_DATA=//table/tbody/tr
VERIFY_SHOPPING_CART_PAGE=.active
PROCEED_TO_CHECKOUT=//a[normalize-space(text())='Proceed To Checkout']
VERIFY_CHECKOUT_POP_UP=//h4[@class='modal-title w-100']
REGISTER_OR_LOGIN=//u[normalize-space(text())='Register / Login']
VERIFY_ADDRESS_DETAIL=//h2[@class='heading'])[1]
VERIFY_REVIEW_YOUR_ORDER=(//h2[@class='heading'])[2]
TYPE_COMMENT_BEFORE_CHECKOUT=//textarea[@class='form-control']
PLACE_ORDER_BUTTON=.btn.btn-default.check_out
DELETE_PRODUCT_BUTTON=.cart_quantity_delete
CART_PRODUCT_NOW=//table[@id='cart_info_table']//tbody/tr